In [3]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Problem 3

## Correct Option a

In [6]:
def count_arr_occurences(arr, value):
    count = 0
    for x in arr:
        if x == value:
            count = count + 1
    return count

In [7]:
count_arr_occurences(make_array(1,3,5,7,7), 7)

2

## Incorrect Option b

In [8]:
def count_arr_occurences_b(arr, value):
    return arr == value

In [9]:
count_arr_occurences_b(make_array(1,3,5,7,7), 7)

array([False, False, False,  True,  True], dtype=bool)

## Incorrect Option c

In [ ]:
def count_arr_occurences_c(arr, value):
    return np.sum(arr = value) # need ==

In [10]:
def count_arr_occurences_c2(arr, value):
    return np.sum(arr == value) # updated

In [11]:
count_arr_occurences_c2(make_array(1,3,5,7,7), 7)

2

## Incorrect Option d

In [12]:
def count_arr_occurences_d(arr, value):
    count = 0
    for i in np.arange(value):
        if arr.item(i) == value:
            count = count + 1
    return count

In [13]:
count_arr_occurences_d(make_array(1,3,5,7,7), 7)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [14]:
count_arr_occurences_d(make_array("dog", "cat"), "dog") # can't do np.arange of a string

TypeError: arange() not supported for inputs with DType <class 'numpy.dtype[str_]'>.

# Question 4

In [18]:
students = Table().with_columns('StudentID', make_array(101, 102, 103, 104, 105), 'Name', make_array('Alica','Bob','Charlie', 'David', 'Eve'))
students = students.with_columns("Age", make_array(20, 21, 19, 22, 20), 'GPA', make_array(3.8, 3.2, 3.5, 3.9, 3.7))
students

StudentID | Name    | Age  | GPA
101       | Alica   | 20   | 3.8
102       | Bob     | 21   | 3.2
103       | Charlie | 19   | 3.5
104       | David   | 22   | 3.9
105       | Eve     | 20   | 3.7

In [19]:
students.where('GPA', are.above(3.5))

StudentID | Name  | Age  | GPA
101       | Alica | 20   | 3.8
104       | David | 22   | 3.9
105       | Eve   | 20   | 3.7

In [20]:
students.where('StudentID', 103)

StudentID | Name    | Age  | GPA
103       | Charlie | 19   | 3.5

In [23]:
students = students.where('Age', are.not_equal_to(19))
students

StudentID | Name  | Age  | GPA
101       | Alica | 20   | 3.8
102       | Bob   | 21   | 3.2
104       | David | 22   | 3.9
105       | Eve   | 20   | 3.7

In [24]:
students.num_rows

4

# Question 5

In [29]:
restaurants = Table().with_columns('Restaurant', make_array("Renata's", "Mazzoti's", "Bayside", "Pho", "Sushi Spot"))
restaurants = restaurants.with_columns('Type', make_array('Cafe', 'Italina', 'Cafe', 'Vietnamese', 'Sushi'))
restaurants = restaurants.with_columns('Distance from Campus', make_array(.5,.7,2,.3,.5))
restaurants

Restaurant | Type       | Distance from Campus
Renata's   | Cafe       | 0.5
Mazzoti's  | Italina    | 0.7
Bayside    | Cafe       | 2
Pho        | Vietnamese | 0.3
Sushi Spot | Sushi      | 0.5

In [31]:
transport = restaurants = Table().with_columns('Restaurant', make_array("Renata's", "Bayside", "Sushi Tao", "Mazotti's", "Mazzotti's"))
transport = transport.with_column("Transportation", make_array('Walk', "Drive", "Bike", "Bike", "Drive"))
transport = transport.with_column("Time", make_array(14, 7, 4, 6, 4))
transport

Restaurant | Transportation | Time
Renata's   | Walk           | 14
Bayside    | Drive          | 7
Sushi Tao  | Bike           | 4
Mazotti's  | Bike           | 6
Mazzotti's | Drive          | 4

In [32]:
def first(some_array):
    return some_array.item(0)

## a 
table with fastest transportation method to get to each restaurant

In [34]:
transport.sort('Time').select("Restaurant", "Transportation").group("Restaurant", first)

Restaurant | Transportation first
Bayside    | Drive
Mazotti's  | Bike
Mazzotti's | Drive
Renata's   | Walk
Sushi Tao  | Bike

## b 
produce table with fastest time for any type of food

In [42]:
restaurants = Table().with_columns('Restaurant', make_array("Renata's", "Mazzoti's", "Bayside", "Pho", "Sushi Spot"))
restaurants = restaurants.with_columns('Type', make_array('Cafe', 'Italina', 'Cafe', 'Vietnamese', 'Sushi'))
restaurants = restaurants.with_columns('Distance from Campus', make_array(.5,.7,2,.3,.5))
restaurants

Restaurant | Type       | Distance from Campus
Renata's   | Cafe       | 0.5
Mazzoti's  | Italina    | 0.7
Bayside    | Cafe       | 2
Pho        | Vietnamese | 0.3
Sushi Spot | Sushi      | 0.5

In [45]:
restaurants.join("Restaurant", transport, "Restaurant").select("Type", "Time").group("Type", first)

Type | Time first
Cafe | 7

## c
produce table with columns corresponding to each unique transportation mode and rows corresponding to each unique restaurant type, cells containing minimum travel time.

In [49]:
restaurants.join("Restaurant", transport, "Restaurant").pivot("Transportation", "Type", "Time", min)

Type | Drive | Walk
Cafe | 7     | 14

## 7 
write function `get_largest` which takes 3 numbers and returns the largest of the three (hint: what if 2 of the numbers are equal?)

In [50]:
def get_largest(a, b, c):
    if a >= b and a >= c:
        largest = a
    elif b >= a and b >= c:
        largest = b
    else:
        largest = c
    return largest

In [51]:
get_largest(1,2,3)

3

In [52]:
get_largest(5,5,7)

7

In [53]:
get_largest(5,5,4)

5

## 8

In [56]:
def tvd(pred, obs):
    return sum(abs(pred - obs))/2

In [57]:
tvd(make_array(1,3,7), make_array(4,2,1))

5.0